remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Puck van Gerwen
description: ML engineer @ Microsoft Azure Quantum
logo: thumbnail.png 
