remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Puck van Gerwen
description: PhD student @ EPFL in developing physics-based machine learning models
logo: VAN-GERWEN-PUCK2304--tojpeg_1544091722068_x2.jpeg
